### ISSUE TITLE
Telemetry_log.timestamp raise time zone support warning

### ISSUE THREAD

**Issue by lyuyangh** [CloudStationTeam/cloud_station_web#13]
**Expected Behavior**
    * Should not give warning
**Detailed Description**
- When new orientation data is received and logged into the db, the following RuntimeWarning is raised:
> DateTimeField Telemetry_log.timestamp received a naive datetime (2019-11-19 08:26:09.096858) while time zone support is active.
- This issue does not raise a problem with the current testing environment, but we will want to add support for different time zones in the future.

**Comment by lyuyangh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/6bQcHf8W/22-test)

**Comment by PeterJBurke** [comment]
no telemetry in v4.0 anymore
