### ISSUE TITLE
Error in map.js 'setData' function undefined

### ISSUE THREAD

**Issue by StevenHe918** [CloudStationTeam/cloud_station_web#18]

**Comment by StevenHe918** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue # 18 Error in map.js 'setData' function undefined](https://trello.com/c/aHOz3F6w/25-issue-18-error-in-mapjs-setdata-function-undefined)

**Comment by lyuyangh** [comment]
I believe @StevenHe918 has fixed this.
