### ISSUE TITLE
use str instead of int for droneid

### ISSUE THREAD

**Issue by lyuyangh** [CloudStationTeam/cloud_station_web#32]
This will provide a way to support more complex ```connect_address``` (ex: "com", "udp:194.xxxxxxx:1234", etc)  Currently, it only supports integers and there are many type casts and ```parseInt()``` which makes it a bad design.

This is related to db, frontend and ```mav_utils```. The interface will need to be changed.

**Comment by PeterJBurke** [comment]
not sure if this matters in v4.0 anymore
